# Generated by Django 5.0.7 on 2024-12-23 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_assign_date',
            field=models.DateField(default=datetime.date(2024, 12, 24)),
        ),
    ]
